openapi: 3.0.0
info:
  title: test-oauth2
  version: '1.0'
  contact:
    name: Camilo Diaz
servers:
  - url: 'https://back-calendar-curso.herokuapp.com/api/'
paths:
  /events:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-events
      security: []
      description: Obtener eventos
      parameters: []
  /auth/loginoauth:
    post:
      summary: ''
      operationId: post-auth-loginoauth
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              description: ''
              type: object
              properties:
                grant_type:
                  type: string
                client_id:
                  type: string
                client_secret:
                  type: string
                scope:
                  type: string
              required:
                - grant_type
                - client_id
                - client_secret
                - scope
        description: ''
components:
  schemas: {}
  securitySchemes: {}
